[build]
  publish = "frontend"
  functions = "api"
  command = "npm install && echo Force rebuild $(date +%s)"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200