[build]
  publish = "frontend"
  functions = "netlify/functions"
  command = "npm install && echo Repointed functions dir $(date +%s)"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ensure function endpoints are not swallowed by the global wildcard redirect
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200